[package]
name = "advent-of-code-2020-rs"
version = "0.1.0"
authors = ["Ross Lannen <ross.lannen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Error handling
anyhow = "1.0.33"
indoc = "1.0.3"
